from pygame.constants import USEREVENT
from pygame.locals import USEREVENT

#--- GAME EVENTS ---#
STARTAI = USEREVENT + 1
PLAYER_ONE_WINS = USEREVENT + 2
PLAYER_TWO_WINS = USEREVENT + 3
DRAW = USEREVENT + 4
UNPAUSED = USEREVENT + 5

#--- MENU EVENTS ---#
MAIN_MENU = USEREVENT + 6
SELECTION_MENU = USEREVENT + 7
PAUSE_MENU = USEREVENT + 8
END_GAME_MENU = USEREVENT + 9
ACTIVATE_GAME = USEREVENT + 10