from pygame.constants import USEREVENT
from pygame.locals import USEREVENT

#--- EVENTS ---#
STARTAI = USEREVENT + 1
PLAYER_ONE_WINS = USEREVENT + 2
PLAYER_TWO_WINS = USEREVENT + 3
DRAW = USEREVENT + 4